spring:
  application:
    name: userService
  cloud:
    discovery:
      client:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/books?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9091
  compression:
    enabled: true
    min-response-size: 6000
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
